name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Package extension
        run: npx vsce package
        working-directory: ./src

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: codezap-vsix
          path: src/*.vsix