name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Must be 18 here
          cache: 'npm'       # Add caching for speed, but we’ll clear it next
          cache-dependency-path: src/package-lock.json

      - name: Install dependencies
        run: npm ci          # Use npm ci for cleaner installs
        working-directory: ./src

      - name: Package extension
        run: npx vsce package
        working-directory: ./src

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: codezap-vsix
          path: src/*.vsix